package com.silverbullet.kode.core.designsystem

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

/**
 * The agent vendors' own logomarks, converted from the SVGs they publish.
 *
 * Unlike [KodeIcons] these are *filled* and carry their own colours, so they
 * are drawn with `Image` rather than a tinted `Icon` — a brand mark recoloured
 * to the foreground is no longer the brand's mark. OpenCode publishes one per
 * colour scheme, so both are here and the theme picks; Claude publishes one.
 *
 * Generated by `core/designsystem/icons/generate_brandmarks.py` from the SVGs
 * in `core/designsystem/icons/brand/`; see the README there.
 */
object KodeBrandMarks {
    /** Claude's logomark, in the one brand colour it is published in. */
    val Claude: ImageVector by lazy {
        brandMark( // claude.ai/favicon.svg
            name = "Claude",
            viewport = 248f,
        ) {
            path(fill = SolidColor(Color(0xFFD97757))) {
                moveTo(52.4285f, 162.873f); lineTo(98.7844f, 136.879f);
                lineTo(99.5485f, 134.602f); lineTo(98.7844f, 133.334f);
                horizontalLineTo(96.4921f); lineTo(88.7237f, 132.862f);
                lineTo(62.2346f, 132.153f); lineTo(39.3113f, 131.207f);
                lineTo(17.0249f, 130.026f); lineTo(11.4214f, 128.844f);
                lineTo(6.2f, 121.873f); lineTo(6.7094f, 118.447f); lineTo(11.4214f, 115.257f);
                lineTo(18.171f, 115.847f); lineTo(33.0711f, 116.911f);
                lineTo(55.485f, 118.447f); lineTo(71.6586f, 119.392f);
                lineTo(95.728f, 121.873f); horizontalLineTo(99.5485f);
                lineTo(100.058f, 120.337f); lineTo(98.7844f, 119.392f);
                lineTo(97.7656f, 118.447f); lineTo(74.5877f, 102.732f);
                lineTo(49.4995f, 86.1905f); lineTo(36.3823f, 76.62f);
                lineTo(29.3779f, 71.7757f); lineTo(25.8121f, 67.2858f);
                lineTo(24.2839f, 57.3608f); lineTo(30.6515f, 50.2716f);
                lineTo(39.3113f, 50.8623f); lineTo(41.4763f, 51.4531f);
                lineTo(50.2636f, 58.1879f); lineTo(68.9842f, 72.7209f);
                lineTo(93.4357f, 90.6804f); lineTo(97.0015f, 93.6343f);
                lineTo(98.4374f, 92.6652f); lineTo(98.6571f, 91.9801f);
                lineTo(97.0015f, 89.2625f); lineTo(83.757f, 65.2772f);
                lineTo(69.621f, 40.8192f); lineTo(63.2534f, 30.6579f);
                lineTo(61.5978f, 24.632f);
                curveTo(60.9565f, 22.1032f, 60.579f, 20.0111f, 60.579f, 17.4246f);
                lineTo(67.8381f, 7.49965f); lineTo(71.9133f, 6.19995f);
                lineTo(81.7193f, 7.49965f); lineTo(85.7946f, 11.0443f);
                lineTo(91.9074f, 24.9865f); lineTo(101.714f, 46.8451f);
                lineTo(116.996f, 76.62f); lineTo(121.453f, 85.4816f);
                lineTo(123.873f, 93.6343f); lineTo(124.764f, 96.1155f);
                horizontalLineTo(126.292f); verticalLineTo(94.6976f);
                lineTo(127.566f, 77.9197f); lineTo(129.858f, 57.3608f);
                lineTo(132.15f, 30.8942f); lineTo(132.915f, 23.4505f);
                lineTo(136.608f, 14.4708f); lineTo(143.994f, 9.62643f);
                lineTo(149.725f, 12.344f); lineTo(154.437f, 19.0788f);
                lineTo(153.8f, 23.4505f); lineTo(150.998f, 41.6463f);
                lineTo(145.522f, 70.1215f); lineTo(141.957f, 89.2625f);
                horizontalLineTo(143.994f); lineTo(146.414f, 86.7813f);
                lineTo(156.093f, 74.0206f); lineTo(172.266f, 53.698f);
                lineTo(179.398f, 45.6635f); lineTo(187.803f, 36.802f);
                lineTo(193.152f, 32.5484f); horizontalLineTo(203.34f);
                lineTo(210.726f, 43.6549f); lineTo(207.415f, 55.1159f);
                lineTo(196.972f, 68.3492f); lineTo(188.312f, 79.5739f);
                lineTo(175.896f, 96.2095f); lineTo(168.191f, 109.585f);
                lineTo(168.882f, 110.689f); lineTo(170.738f, 110.53f);
                lineTo(198.755f, 104.504f); lineTo(213.91f, 101.787f);
                lineTo(231.994f, 98.7149f); lineTo(240.144f, 102.496f);
                lineTo(241.036f, 106.395f); lineTo(237.852f, 114.311f);
                lineTo(218.495f, 119.037f); lineTo(195.826f, 123.645f);
                lineTo(162.07f, 131.592f); lineTo(161.696f, 131.893f);
                lineTo(162.137f, 132.547f); lineTo(177.36f, 133.925f);
                lineTo(183.855f, 134.279f); horizontalLineTo(199.774f);
                lineTo(229.447f, 136.524f); lineTo(237.215f, 141.605f);
                lineTo(241.8f, 147.867f); lineTo(241.036f, 152.711f);
                lineTo(229.065f, 158.737f); lineTo(213.019f, 154.956f);
                lineTo(175.45f, 145.977f); lineTo(162.587f, 142.787f);
                horizontalLineTo(160.805f); verticalLineTo(143.85f);
                lineTo(171.502f, 154.366f); lineTo(191.242f, 172.089f);
                lineTo(215.82f, 195.011f); lineTo(217.094f, 200.682f);
                lineTo(213.91f, 205.172f); lineTo(210.599f, 204.699f);
                lineTo(188.949f, 188.394f); lineTo(180.544f, 181.069f);
                lineTo(161.696f, 165.118f); horizontalLineTo(160.422f);
                verticalLineTo(166.772f); lineTo(164.752f, 173.152f);
                lineTo(187.803f, 207.771f); lineTo(188.949f, 218.405f);
                lineTo(187.294f, 221.832f); lineTo(181.308f, 223.959f);
                lineTo(174.813f, 222.777f); lineTo(161.187f, 203.754f);
                lineTo(147.305f, 182.486f); lineTo(136.098f, 163.345f);
                lineTo(134.745f, 164.2f); lineTo(128.075f, 235.42f);
                lineTo(125.019f, 239.082f); lineTo(117.887f, 241.8f);
                lineTo(111.902f, 237.31f); lineTo(108.718f, 229.984f);
                lineTo(111.902f, 215.452f); lineTo(115.722f, 196.547f);
                lineTo(118.779f, 181.541f); lineTo(121.58f, 162.873f);
                lineTo(123.291f, 156.636f); lineTo(123.14f, 156.219f);
                lineTo(121.773f, 156.449f); lineTo(107.699f, 175.752f);
                lineTo(86.304f, 204.699f); lineTo(69.3663f, 222.777f);
                lineTo(65.291f, 224.431f); lineTo(58.2867f, 220.768f);
                lineTo(58.9235f, 214.27f); lineTo(62.8713f, 208.48f);
                lineTo(86.304f, 178.705f); lineTo(100.44f, 160.155f);
                lineTo(109.551f, 149.507f); lineTo(109.462f, 147.967f);
                lineTo(108.959f, 147.924f); lineTo(46.6977f, 188.512f);
                lineTo(35.6182f, 189.93f); lineTo(30.7788f, 185.44f);
                lineTo(31.4156f, 178.115f); lineTo(33.7079f, 175.752f);
                lineTo(52.4285f, 162.873f); close()
            }
        }
    }

    /** OpenCode's mark in its official dark-scheme colours. */
    val OpenCodeDark: ImageVector by lazy {
        brandMark( // sst/opencode packages/identity/mark.svg
            name = "OpenCodeDark",
            viewport = 320f,
            offsetX = -96f,
            offsetY = -96f,
        ) {
            path(fill = SolidColor(Color(0xFF5A5858))) {
                moveTo(320f, 224f); verticalLineTo(352f); horizontalLineTo(192f);
                verticalLineTo(224f); horizontalLineTo(320f); close()
            }
            path(fill = SolidColor(Color(0xFFFFFFFF)), pathFillType = PathFillType.EvenOdd) {
                moveTo(384f, 416f); horizontalLineTo(128f); verticalLineTo(96f);
                horizontalLineTo(384f); verticalLineTo(416f); close()
                moveTo(320f, 160f); horizontalLineTo(192f); verticalLineTo(352f);
                horizontalLineTo(320f); verticalLineTo(160f); close()
            }
        }
    }

    /** OpenCode's mark in its official light-scheme colours. */
    val OpenCodeLight: ImageVector by lazy {
        brandMark( // sst/opencode packages/identity/mark-light.svg
            name = "OpenCodeLight",
            viewport = 320f,
            offsetX = -96f,
            offsetY = -96f,
        ) {
            path(fill = SolidColor(Color(0xFFE6E5E6))) {
                moveTo(320f, 224f); verticalLineTo(352f); horizontalLineTo(192f);
                verticalLineTo(224f); horizontalLineTo(320f); close()
            }
            path(fill = SolidColor(Color(0xFF17181C)), pathFillType = PathFillType.EvenOdd) {
                moveTo(384f, 416f); horizontalLineTo(128f); verticalLineTo(96f);
                horizontalLineTo(384f); verticalLineTo(416f); close()
                moveTo(320f, 160f); horizontalLineTo(192f); verticalLineTo(352f);
                horizontalLineTo(320f); verticalLineTo(160f); close()
            }
        }
    }
}

/**
 * A filled brand mark on a square viewport.
 *
 * [offsetX]/[offsetY] translate the glyph's window within the source `viewBox`
 * to the origin and centre its narrower axis, so callers can size a mark with a
 * square `Modifier.size` exactly like a [KodeIcons] glyph.
 */
private fun brandMark(
    name: String,
    viewport: Float,
    offsetX: Float = 0f,
    offsetY: Float = 0f,
    paths: ImageVector.Builder.() -> Unit,
): ImageVector = ImageVector.Builder(
    name = name,
    defaultWidth = 24.dp,
    defaultHeight = 24.dp,
    viewportWidth = viewport,
    viewportHeight = viewport,
).apply {
    if (offsetX == 0f && offsetY == 0f) {
        paths()
    } else {
        group(translationX = offsetX, translationY = offsetY) { paths() }
    }
}.build()
