import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from svg_to_imagevector import shapes

# One entry per generated `ImageVector`.
#
# `window` is the glyph's box within the source `viewBox`, as (x, y, w, h). The
# brand marks are published as app icons, so their glyph sits inset inside a
# background plate; the window is read straight off the outermost glyph path's
# own extents. `fills` maps every fill the SVG uses to the Kotlin colour to draw
# it with, or to None to drop it — the background plate is the only thing
# dropped. An unlisted fill is an error rather than a silent omission.
MARKS = [
    dict(
        name="Claude",
        slug="brand/claude",
        source="claude.ai/favicon.svg",
        window=(0, 0, 248, 248),
        fills={"#D97757": "Color(0xFFD97757)"},
        doc="Claude's logomark, in the one brand colour it is published in.",
    ),
    dict(
        name="OpenCodeDark",
        slug="brand/opencode-dark",
        source="sst/opencode packages/identity/mark.svg",
        window=(128, 96, 256, 320),
        fills={
            "#131010": None,  # the app icon's background plate
            "#5A5858": "Color(0xFF5A5858)",
            "white": "Color(0xFFFFFFFF)",
        },
        doc="OpenCode's mark in its official dark-scheme colours.",
    ),
    dict(
        name="OpenCodeLight",
        slug="brand/opencode-light",
        source="sst/opencode packages/identity/mark-light.svg",
        window=(128, 96, 256, 320),
        fills={
            "#FDFCFC": None,  # the app icon's background plate
            "#E6E5E6": "Color(0xFFE6E5E6)",
            "#17181C": "Color(0xFF17181C)",
        },
        doc="OpenCode's mark in its official light-scheme colours.",
    ),
]

SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__))
LIMIT = 94


def wrap(line, indent):
    """Re-flow a `;`-joined subpath so the generated source stays readable."""
    calls = line.split('; ')
    out, buf = [], ''
    for call in calls:
        cand = call if not buf else buf + '; ' + call
        if buf and len(indent) + len(cand) + 1 > LIMIT:
            out.append(indent + buf + ';')
            buf = call
        else:
            buf = cand
    if buf:
        out.append(indent + buf)
    return out


head = '''package com.silverbullet.kode.core.designsystem

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.group
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

/**
 * The agent vendors' own logomarks, converted from the SVGs they publish.
 *
 * Unlike [KodeIcons] these are *filled* and carry their own colours, so they
 * are drawn with `Image` rather than a tinted `Icon` — a brand mark recoloured
 * to the foreground is no longer the brand's mark. OpenCode publishes one per
 * colour scheme, so both are here and the theme picks; Claude publishes one.
 *
 * Generated by `core/designsystem/icons/generate_brandmarks.py` from the SVGs
 * in `core/designsystem/icons/brand/`; see the README there.
 */
object KodeBrandMarks {'''

body = []
for mark in MARKS:
    x, y, w, h = mark["window"]
    viewport = float(max(w, h))
    offset_x = -x + (viewport - w) / 2
    offset_y = -y + (viewport - h) / 2
    indent = ' ' * 12

    body.append('')
    body.append('    /** %s */' % mark["doc"])
    body.append('    val %s: ImageVector by lazy {' % mark["name"])
    body.append('        brandMark( // %s' % mark["source"])
    body.append('            name = "%s",' % mark["name"])
    body.append('            viewport = %gf,' % viewport)
    if offset_x or offset_y:
        body.append('            offsetX = %gf,' % offset_x)
        body.append('            offsetY = %gf,' % offset_y)
    body.append('        ) {')

    drawn = 0
    for fill, even_odd, lines in shapes(open(os.path.join(SRC, mark["slug"] + '.svg')).read()):
        if fill not in mark["fills"]:
            raise ValueError('%s: unmapped fill %r' % (mark["name"], fill))
        colour = mark["fills"][fill]
        if colour is None:
            continue
        drawn += 1
        args = ['fill = SolidColor(%s)' % colour]
        if even_odd:
            args.append('pathFillType = PathFillType.EvenOdd')
        body.append('%spath(%s) {' % (indent, ', '.join(args)))
        for line in lines:
            body.extend(wrap(line.strip(), indent + '    '))
        body.append('%s}' % indent)
    if drawn == 0:
        raise ValueError('%s: every shape was dropped' % mark["name"])

    body.append('        }')
    body.append('    }')

tail = '''}

/**
 * A filled brand mark on a square viewport.
 *
 * [offsetX]/[offsetY] translate the glyph's window within the source `viewBox`
 * to the origin and centre its narrower axis, so callers can size a mark with a
 * square `Modifier.size` exactly like a [KodeIcons] glyph.
 */
private fun brandMark(
    name: String,
    viewport: Float,
    offsetX: Float = 0f,
    offsetY: Float = 0f,
    paths: ImageVector.Builder.() -> Unit,
): ImageVector = ImageVector.Builder(
    name = name,
    defaultWidth = 24.dp,
    defaultHeight = 24.dp,
    viewportWidth = viewport,
    viewportHeight = viewport,
).apply {
    if (offsetX == 0f && offsetY == 0f) {
        paths()
    } else {
        group(translationX = offsetX, translationY = offsetY) { paths() }
    }
}.build()
'''

if __name__ == '__main__':
    print(head + '\n'.join(body) + '\n' + tail, end='')
